## Standard Imports 

In [1]:
import numpy as np

import tensorflow as tf

from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.losses import SparseCategoricalCrossentropy

### Binary Cross Entropy Loss

In [2]:
true_values = np.array([[1.,0.],[1.,0.],[0.,1.]])
predictions = np.array([[.9,.1], [.7,.3],[.4,.6]])

In [3]:
true_values[0], predictions[0]

(array([1., 0.]), array([0.9, 0.1]))

In [4]:
bce_loss_first = -(1 * np.log(0.9) + (1-1)*np.log(0.1))
bce_loss_first

0.10536051565782628

In [5]:
true_values[1], predictions[1]

(array([1., 0.]), array([0.7, 0.3]))

In [6]:
bce_loss_second = -(1 * np.log(0.7) + (1-1)*np.log(0.3))
bce_loss_second

0.35667494393873245

In [7]:
true_values[2], predictions[2]

(array([0., 1.]), array([0.4, 0.6]))

In [8]:
bce_loss_third = -(1 * np.log(0.6) + (1-1)*np.log(0.4))

In [9]:
loss = (bce_loss_first + bce_loss_second + bce_loss_third)/3
loss

0.3242870277875165

In [10]:
bce_loss = BinaryCrossentropy()

In [11]:
m = tf.cast([[1.,0.],[1.,0.],[0.,1.]], tf.float32)
n = tf.cast([[.9,.1], [.7,.3], [.4,.6]], tf.float32)

In [12]:
loss = bce_loss(m,n).numpy()
loss

0.32428685

In [13]:
def binary_cross_entropy(true_values,predictions):
    y_true = tf.cast(true_values,dtype=tf.float32)
    y_pred = tf.cast(predictions,dtype=tf.float32)
    X = tf.multiply(m,tf.math.log(n))
    return (-tf.reduce_sum(X)/len(n)).numpy()

In [14]:
loss = binary_cross_entropy([[1.,0.],[1.,0.],[0.,1.]], [[.9,.1], [.7,.3], [.4,.6]])
loss

0.32428703

## Categorical Cross Entropy 

In [15]:
true_values = [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]
predictions = [[.9, .05, .05], [.05, .89, .06], [.05, .01, .94]]

In [16]:
true_values[0], predictions[0]

([1.0, 0.0, 0.0], [0.9, 0.05, 0.05])

In [17]:
cce_loss_first = -(1 * np.log(0.9))
cce_loss_first

0.10536051565782628

In [18]:
true_values[1], predictions[1]

([0.0, 1.0, 0.0], [0.05, 0.89, 0.06])

In [19]:
cce_loss_second = -(1 * np.log(0.89))
cce_loss_second

0.11653381625595151

In [20]:
true_values[2], predictions[2]

([0.0, 0.0, 1.0], [0.05, 0.01, 0.94])

In [21]:
cce_loss_third = -(1 * np.log(0.94))
cce_loss_third

0.06187540371808753

In [22]:
loss = (cce_loss_first + cce_loss_second + cce_loss_third)/3
loss

0.09458991187728844

In [23]:
cce_loss = CategoricalCrossentropy()
loss = cce_loss(true_values,predictions).numpy()
loss

0.09458993

In [24]:
def categorical_cross_entropy(true_values,predictions):
    y_true = tf.cast(true_values,dtype=tf.float32)
    y_pred = tf.cast(predictions,dtype=tf.float32)
    X = tf.multiply(y_true,tf.math.log(y_pred))
    return (-tf.reduce_sum(X)/len(y_true)).numpy()

In [25]:
loss = categorical_cross_entropy(true_values,predictions)
loss

0.09458993

### Sparse Categorical Cross Entropy

In [26]:
true_values = [1,0,2, 1, 2,0]
predictions = [
    [.05, .9, .05],
    [.89, .05, .06],
    [.05, .01, .94],
    [.1, .8, .1],
    [.7, .2, .1],
    [.08, .05, .87]
]

In [27]:
true_values = np.array(true_values)
predictions = np.array(predictions)

In [28]:
true_values, predictions

(array([1, 0, 2, 1, 2, 0]),
 array([[0.05, 0.9 , 0.05],
        [0.89, 0.05, 0.06],
        [0.05, 0.01, 0.94],
        [0.1 , 0.8 , 0.1 ],
        [0.7 , 0.2 , 0.1 ],
        [0.08, 0.05, 0.87]]))

In [29]:
individual_ce_losses = [-np.log(predictions[i][true_values[i]]) 
for i in range(len(true_values))]

In [30]:
loss = np.mean(individual_ce_losses)
loss

0.8892045040413961

In [31]:
cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce(
    tf.cast(true_values,dtype=tf.float32),
    tf.cast(predictions, dtype=tf.float32)
).numpy()
loss

0.8892045

In [32]:
def sparse_categorical_cross_entropy(true_values, predictions):
    y_t = tf.cast(true_values,dtype=tf.int32)
    y_p = tf.cast(predictions,dtype=tf.float32)
    losses = [-np.log(y_p[i][y_t[i]]) for i in range(len(y_t))]
    return np.mean(losses)

In [33]:
sparse_categorical_cross_entropy(true_values,predictions)

0.8892045