In [1]:
import numpy as np

In [14]:
X = np.random.randint(low=1, high=100, size=6)

In [15]:
X

array([96, 85,  2, 29, 31, 74])

In [22]:
for i in X:
    print(i)

96
85
2
29
31
74


In [96]:
def mean(x):
    x = np.array(x)
    return sum(x)/len(x)

In [18]:
np.round(mean(X),2)

52.83

In [21]:
for i in np.round(X - mean(X),2):
    print(i)

43.17
32.17
-50.83
-23.83
-21.83
21.17


In [26]:
for i in np.round(np.power(X - mean(X),2),2):
    print(i)

1863.36
1034.69
2584.03
568.03
476.69
448.03


In [29]:
for i in np.round(np.power(X - mean(X),2)/len(X) ,2):
    print(i)

310.56
172.45
430.67
94.67
79.45
74.67


In [31]:
np.sum(np.round(np.power(X - mean(X),2)/len(X) ,2))

1162.47

In [32]:
np.var(X)

1162.4722222222222

In [33]:
X = np.random.randint(low=1, high=20, size=6)

In [34]:
Y = np.random.randint(low=1, high=20, size=6)

In [35]:
X

array([16, 14, 19, 12, 19, 15])

In [37]:
for i in X:
    print(i)

16
14
19
12
19
15


In [36]:
Y

array([ 2,  1, 11,  1, 14, 18])

In [38]:
for i in Y:
    print(i)

2
1
11
1
14
18


In [42]:
np.round(mean(X),2)

15.83

In [41]:
np.round(mean(Y),2)

7.83

In [47]:
np.round(X - mean(X),2)

array([ 0.17, -1.83,  3.17, -3.83,  3.17, -0.83])

In [48]:
np.round(Y-mean(Y),2)

array([-5.83, -6.83,  3.17, -6.83,  6.17, 10.17])

In [53]:
np.round(((X - mean(X)) * (Y - mean(Y)))/6, 2)

array([-0.16,  2.09,  1.67,  4.37,  3.25, -1.41])

In [55]:
sum(((X - mean(X)) * (Y - mean(Y)))/6)

9.805555555555555

In [56]:
np.round(sum(((X - mean(X)) * (Y - mean(Y)))/6), 2)

9.81

In [57]:
def sample_std(x):
    temp = x - mean(x)
    temp = temp**2
    temp = sum(temp)
    temp = temp/(len(x) - 1)
    temp = temp**(0.5)
    return temp

In [58]:
sample_std(X)

2.7868739954771304

In [59]:
sample_std(Y)

7.467708260682569

In [62]:
np.cov(X,Y)

array([[ 7.76666667, 11.76666667],
       [11.76666667, 55.76666667]])

In [63]:
X

array([16, 14, 19, 12, 19, 15])

In [64]:
Y

array([ 2,  1, 11,  1, 14, 18])

In [65]:
np.corrcoef(X,Y)

array([[1.        , 0.56539085],
       [0.56539085, 1.        ]])

In [66]:
np.var(X)

6.472222222222221

In [67]:
np.var(Y)

46.47222222222223

In [87]:
def variance(x):
    x = x - mean(x)
    x = x**2
    return np.round(sum(x)/len(x),2)

In [90]:
variance(np.array([96, 85,  2, 29, 31, 74]))

1162.47

In [70]:
sample_variance(Y)

46.47222222222223

In [112]:
def covariance(x,y):
    x = np.array(x)
    y = np.array(y)
    x = x - mean(x)
    y = y - mean(y)
    temp = x * y
    temp = temp/(len(x) - 1)
    return sum(temp)

In [80]:
covariance(X,Y)

11.77

In [97]:
def variance(x):
    x = np.array(x)
    x = x - mean(x)
    x = x**2
    return np.round(sum(x)/len(x),2)

In [98]:
x = [96, 85,  2, 29, 31, 74]

In [99]:
variance(x)

1162.47

In [93]:
sum(x)

317

In [94]:
mean(x)

52.833333333333336

In [100]:
def sample_variance(x):
    x = np.array(x)
    x = x - mean(x)
    x = x**2
    return np.round(sum(x)/(len(x) - 1),2)

In [101]:
sample_variance(x)

1394.97

In [102]:
def sample_std(x):
    return sample_variance(x)**(0.5)

In [103]:
sample_std(x)

37.34929718214253

In [104]:
X

array([16, 14, 19, 12, 19, 15])

In [105]:
Y

array([ 2,  1, 11,  1, 14, 18])

In [117]:
def correlation(x,y):
    cov = covariance(x,y)
    return cov/(sample_std(x) * sample_std(y))

In [118]:
correlation(X,Y)

0.565252665558361

In [115]:
np.corrcoef(X,Y)

array([[1.        , 0.56539085],
       [0.56539085, 1.        ]])

In [113]:
covariance(X,Y)

11.766666666666666

In [114]:
np.cov(X,Y)

array([[ 7.76666667, 11.76666667],
       [11.76666667, 55.76666667]])